# Generated by Django 3.0.8 on 2021-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Organization name')),
                ('description', models.TextField(help_text='Organization description')),
                ('website', models.TextField(help_text='Organization website')),
                ('org_type', models.TextField(help_text='Organization type')),
            ],
        ),
    ]
