site_name: coalesce
site_description: An open source volunteer management platform
repo_url: https://github.com/FederationOfTech/coalesce
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/FederationOfTech">FederationOfTech</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
