# Generated by Django 3.0.8 on 2021-04-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='organizer_comments',
            field=models.TextField(help_text='Notes from organizers about this volunteer'),
        ),
    ]
