# Generated by Django 3.0.8 on 2021-04-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(),
        ),
    ]
