# Generated by Django 3.0.8 on 2020-11-26 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
