# Generated by Django 3.0.8 on 2020-11-27 13:29

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('background_check_requirements', models.TextField()),
                ('commitment_type', models.TextField()),
                ('datetime', models.DateTimeField(blank=True, help_text='Event date')),
                ('description', models.TextField()),
                ('clothing_requirements', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('personnel_needed', models.IntegerField()),
                ('post_privacy', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('unlisted', 'unlisted')], default='public', max_length=8)),
                ('skills_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), size=None)),
                ('title', models.CharField(max_length=60)),
            ],
        ),
    ]
