# Generated by Django 3.0.8 on 2020-11-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='organizers',
            field=models.ManyToManyField(to='organizers.Organizer'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='clothing_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
