# Generated by Django 3.0.8 on 2020-11-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='clothing_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
