# Generated by Django 3.0.8 on 2020-11-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
